# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "hwenjun"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Reshaping":
        filters: ["Reshaping", "Shape", "Human-body Retouching", "Face Animation", "Flow", "Structure Editing"]
    "Portrait ":
        filters: ["Portrait ", "Face", "Enhance", "MakeUp", "Tone", "Relight", "Bokeh", "Harmonization", "Harmony"]
    "GAN":
        filters: ["GAN","StyleGAN", "Style Transfer","Generative Adversarial Network"]
    "GPT":
        filters: ["GPT","LLM"]   
    "Transfomer":
        filters: ["Transfomer"] 
    "Diffusion Model":
        filters: ["Diffusion Model", "Diffusion", "DDPM", "Clip", "Text-to-Image"]
    "Image Edit":
        filters: ["Image Retouching", "Face Edit", "Image Edit", "Retouch", "Image Restoration", "Inpainting"]
    "NeRF":
        filters: ["NeRF", "MVS", "Neural Rendering", "Neus"]
